
USE ROLE ROLE_TEAM_VRR;
USE WAREHOUSE ANIMAL_TASK_WH;
USE DATABASE DB_TEAM_VRR;

-- Now create sub-schemas for your project (Bronze/Silver/Gold)
CREATE SCHEMA IF NOT EXISTS DB_TEAM_VRR.BRONZE;
CREATE SCHEMA IF NOT EXISTS DB_TEAM_VRR.SILVER;
CREATE SCHEMA IF NOT EXISTS DB_TEAM_VRR.GOLD;



CREATE OR REPLACE STAGE DB_TEAM_VRR.BRONZE.BRONZE_INGEST_STAGE
  FILE_FORMAT = DB_TEAM_VRR.BRONZE.CSV_FF
  COMMENT = 'Bronze ingest stage for CSV loads';

-- Minimal parser: this doesn’t change values; it only tells Snowflake how to read CSV.
CREATE OR REPLACE FILE FORMAT CSV_FF
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE TABLE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@DB_TEAM_VRR.BRONZE.BRONZE_INGEST_STAGE',
      FILE_FORMAT => 'DB_TEAM_VRR.BRONZE.CSV_FF',
      FILES => ('youtube_channel_info_v1.csv')
    )
  )
);


CREATE OR REPLACE FILE FORMAT DB_TEAM_VRR.BRONZE.CSV_FF
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    PARSE_HEADER = TRUE;

    

COPY INTO DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
FROM @DB_TEAM_VRR.BRONZE.BRONZE_INGEST_STAGE
FILE_FORMAT = (FORMAT_NAME = 'DB_TEAM_VRR.BRONZE.CSV_FF')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';


select count(*) from BRONZE.YOUTUBE_CHANNELS_RAW


-- =========================================================
-- AI SQL ENRICHMENT ON BRONZE.YOUTUBE_CHANNELS_RAW
-- =========================================================

USE ROLE ROLE_TEAM_VRR;
USE WAREHOUSE ANIMAL_TASK_WH;
USE DATABASE DB_TEAM_VRR;
USE SCHEMA BRONZE;

-- 1) Add AI columns (safe to re-run because of IF NOT EXISTS)
ALTER TABLE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW 
    ADD COLUMN IF NOT EXISTS AI_SENTIMENT_SCORE FLOAT;

ALTER TABLE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW 
    ADD COLUMN IF NOT EXISTS AI_SENTIMENT_LABEL STRING;

ALTER TABLE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW 
    ADD COLUMN IF NOT EXISTS AI_TOPIC STRING;

ALTER TABLE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW 
    ADD COLUMN IF NOT EXISTS AI_DESCRIPTION_SUM STRING;


----------------------------
---Populate AI Sentiment Score
-------------------------------

UPDATE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
SET AI_SENTIMENT_SCORE = SNOWFLAKE.CORTEX.SENTIMENT("description");

-------------------------
----Populate Sentiment Label
-------------------------

UPDATE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
SET AI_SENTIMENT_LABEL =
    CASE 
        WHEN AI_SENTIMENT_SCORE >  0.25 THEN 'Positive'
        WHEN AI_SENTIMENT_SCORE < -0.25 THEN 'Negative'
        ELSE 'Neutral'
    END;

-----------------
---Classify Topic
-----------------

UPDATE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
SET AI_TOPIC =
    SNOWFLAKE.CORTEX.AI_CLASSIFY(
        "description",
        ['music', 'gaming', 'education', 'entertainment', 'news']
    ):"label"::string;

--------------
--Summarize Description
--------------

UPDATE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
SET AI_DESCRIPTION_SUM = SNOWFLAKE.CORTEX.SUMMARIZE("description");


SELECT
    "channel_id",
    "channel_name",
    AI_SENTIMENT_SCORE,
    AI_SENTIMENT_LABEL,
    AI_TOPIC,
    AI_DESCRIPTION_SUM
FROM DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
LIMIT 10;
