USE ROLE ROLE_TEAM_VRR;
USE DATABASE DB_TEAM_VRR;
USE SCHEMA SILVER;

-- 1a) Country dimension
CREATE OR REPLACE TABLE SILVER.DIM_COUNTRY (
    COUNTRY_SK NUMBER IDENTITY(1,1),
    COUNTRY_CODE  VARCHAR,
    CONSTRAINT PK_DIM_COUNTRY PRIMARY KEY (COUNTRY_SK),
    CONSTRAINT UQ_DIM_COUNTRY_CODE UNIQUE (COUNTRY_CODE)
);

-- 1b) Category dimension
CREATE OR REPLACE TABLE SILVER.DIM_CATEGORY (
    CATEGORY_SK    NUMBER IDENTITY(1,1),
    CATEGORY_NAME  VARCHAR,
    CONSTRAINT PK_DIM_CATEGORY PRIMARY KEY (CATEGORY_SK),
    CONSTRAINT UQ_DIM_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);

-- 1c) Channel dimension
CREATE OR REPLACE TABLE SILVER.DIM_CHANNEL (
    CHANNEL_SK       NUMBER IDENTITY(1,1),
    CHANNEL_ID       VARCHAR,       -- natural key from source (YouTube)
    CHANNEL_NAME     VARCHAR,
    DESCRIPTION      VARCHAR,
    CUSTOM_URL       VARCHAR,
    THUMBNAIL        VARCHAR,
    CREATED_DATE     DATE,
    CATEGORY_SK      NUMBER,
    COUNTRY_SK       NUMBER,
    DEFAULT_LANGUAGE VARCHAR,
    CONSTRAINT PK_DIM_CHANNEL PRIMARY KEY (CHANNEL_SK),
    CONSTRAINT UQ_DIM_CHANNEL_CHANNEL_ID UNIQUE (CHANNEL_ID),
    CONSTRAINT FK_DIM_CHANNEL_COUNTRY
        FOREIGN KEY (COUNTRY_SK) REFERENCES SILVER.DIM_COUNTRY(COUNTRY_SK),
    CONSTRAINT FK_DIM_CHANNEL_CATEGORY
        FOREIGN KEY (CATEGORY_SK) REFERENCES SILVER.DIM_CATEGORY(CATEGORY_SK)
);

-- 2. Fact table using surrogate key (CHANNEL_SK)
CREATE OR REPLACE TABLE SILVER.FACT_CHANNEL_METRICS (
    CHANNEL_SK        NUMBER,
    LOAD_DATE         DATE,
    VIEW_COUNT        NUMBER,
    SUBSCRIBER_COUNT  NUMBER,
    VIDEO_COUNT       NUMBER,
    CONSTRAINT PK_FACT_CHANNEL PRIMARY KEY (CHANNEL_SK, LOAD_DATE),
    CONSTRAINT FK_FACT_CHANNEL_DIM_CHANNEL
        FOREIGN KEY (CHANNEL_SK) REFERENCES SILVER.DIM_CHANNEL(CHANNEL_SK)
);

-- 3. Composite / summary table: AGG_COUNTRY_METRICS
CREATE OR REPLACE TABLE SILVER.AGG_COUNTRY_METRICS (
    COUNTRY_SK             NUMBER,
    LOAD_DATE              DATE,
    TOTAL_CHANNELS         NUMBER,
    TOTAL_VIEWS            NUMBER,
    TOTAL_SUBSCRIBERS      NUMBER,
    TOTAL_VIDEOS           NUMBER,
    AVG_VIEWS_PER_CHANNEL  NUMBER,
    AVG_SUBS_PER_CHANNEL   NUMBER,
    CONSTRAINT FK_AGG_COUNTRY_DIM_COUNTRY
        FOREIGN KEY (COUNTRY_SK) REFERENCES SILVER.DIM_COUNTRY(COUNTRY_SK)
);

SELECT *
FROM DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW
LIMIT 5;

DESCRIBE TABLE DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW;

-- 4. Load small dimension tables from Bronze
-- 4a) DIM_COUNTRY
INSERT INTO SILVER.DIM_COUNTRY (COUNTRY_CODE)
SELECT DISTINCT
    TRIM(r."country") AS COUNTRY_CODE
FROM DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW r
WHERE r."country" IS NOT NULL;

-- DIM_CATEGORY
INSERT INTO SILVER.DIM_CATEGORY (CATEGORY_NAME)
SELECT DISTINCT
    TRIM(r."category") AS CATEGORY_NAME
FROM DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW r
WHERE r."category" IS NOT NULL;

-- DIM_CHANNEL
INSERT INTO SILVER.DIM_CHANNEL (
    CHANNEL_ID,
    CHANNEL_NAME,
    DESCRIPTION,
    CUSTOM_URL,
    THUMBNAIL,
    CREATED_DATE,
    CATEGORY_SK,
    COUNTRY_SK,
    DEFAULT_LANGUAGE
)
SELECT DISTINCT
    r."channel_id",
    r."channel_name",
    r."description",
    r."custom_url",
    r."thumbnail",
    CAST(r."created_date" AS DATE)    AS created_date,
    cat.CATEGORY_SK,
    co.COUNTRY_SK,
    r."defaultLanguage"              AS DEFAULT_LANGUAGE
FROM DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW r
LEFT JOIN SILVER.DIM_CATEGORY cat
       ON TRIM(r."category") = cat.CATEGORY_NAME
LEFT JOIN SILVER.DIM_COUNTRY  co
       ON TRIM(r."country")  = co.COUNTRY_CODE;

-- FACT_CHANNEL_METRICS
INSERT INTO SILVER.FACT_CHANNEL_METRICS (
    CHANNEL_SK,
    LOAD_DATE,
    VIEW_COUNT,
    SUBSCRIBER_COUNT,
    VIDEO_COUNT
)
SELECT
    ch.CHANNEL_SK,
    CURRENT_DATE            AS LOAD_DATE,
    r."view_count",
    r."subscriber_count",
    r."video_count"
FROM DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW r
JOIN SILVER.DIM_CHANNEL ch
  ON ch.CHANNEL_ID = r."channel_id";

SHOW TABLES IN SCHEMA SILVER;

SELECT * FROM SILVER.DIM_COUNTRY   LIMIT 10;
SELECT * FROM SILVER.DIM_CATEGORY  LIMIT 10;
SELECT * FROM SILVER.DIM_CHANNEL   LIMIT 10;
SELECT * FROM SILVER.FACT_CHANNEL_METRICS LIMIT 10;
SELECT * FROM SILVER.AGG_COUNTRY_METRICS;
SELECT COUNT(*) AS fact_rows
FROM SILVER.FACT_CHANNEL_METRICS;

INSERT INTO SILVER.AGG_COUNTRY_METRICS (
    COUNTRY_SK,
    LOAD_DATE,
    TOTAL_CHANNELS,
    TOTAL_VIEWS,
    TOTAL_SUBSCRIBERS,
    TOTAL_VIDEOS,
    AVG_VIEWS_PER_CHANNEL,
    AVG_SUBS_PER_CHANNEL
)
SELECT
    co.COUNTRY_SK,
    f.LOAD_DATE,
    COUNT(DISTINCT f.CHANNEL_SK) AS TOTAL_CHANNELS,
    SUM(f.VIEW_COUNT)            AS TOTAL_VIEWS,
    SUM(f.SUBSCRIBER_COUNT)      AS TOTAL_SUBSCRIBERS,
    SUM(f.VIDEO_COUNT)           AS TOTAL_VIDEOS,
    AVG(f.VIEW_COUNT)            AS AVG_VIEWS_PER_CHANNEL,
    AVG(f.SUBSCRIBER_COUNT)      AS AVG_SUBS_PER_CHANNEL
FROM SILVER.FACT_CHANNEL_METRICS f
JOIN SILVER.DIM_CHANNEL ch
  ON f.CHANNEL_SK = ch.CHANNEL_SK
JOIN SILVER.DIM_COUNTRY co
  ON ch.COUNTRY_SK = co.COUNTRY_SK
GROUP BY co.COUNTRY_SK, f.LOAD_DATE;

SELECT COUNT(*) FROM SILVER.AGG_COUNTRY_METRICS;
SELECT * FROM SILVER.AGG_COUNTRY_METRICS LIMIT 10;

-- 1) Bronze: total rows and distinct channels
SELECT
  COUNT(*)                         AS bronze_rows,
  COUNT(DISTINCT "channel_id")     AS bronze_distinct_channels
FROM DB_TEAM_VRR.BRONZE.YOUTUBE_CHANNELS_RAW;

-- 2) Fact: total rows, distinct channels, distinct load dates
SELECT
  COUNT(*)                    AS fact_rows,
  COUNT(DISTINCT CHANNEL_SK)  AS fact_distinct_channels,
  COUNT(DISTINCT LOAD_DATE)   AS fact_distinct_load_dates
FROM SILVER.FACT_CHANNEL_METRICS;

CREATE OR REPLACE VIEW V_YOUTUBE_CHANNEL_ANALYTICS AS
SELECT
    f.LOAD_DATE,
    ch.CHANNEL_ID,
    ch.CHANNEL_NAME,
    cat.CATEGORY_NAME      AS CATEGORY,
    co.COUNTRY_CODE        AS COUNTRY,
    ch.DEFAULT_LANGUAGE,
    f.VIEW_COUNT,
    f.SUBSCRIBER_COUNT,
    f.VIDEO_COUNT
FROM SILVER.FACT_CHANNEL_METRICS f
JOIN SILVER.DIM_CHANNEL ch
      ON f.CHANNEL_SK = ch.CHANNEL_SK
LEFT JOIN SILVER.DIM_CATEGORY cat
      ON ch.CATEGORY_SK = cat.CATEGORY_SK
LEFT JOIN SILVER.DIM_COUNTRY co
      ON ch.COUNTRY_SK = co.COUNTRY_SK;
